### ISSUE TITLE
Nomination myself to Take over Arabic Translation maintainer

### ISSUE THREAD

**Issue by A7med3bdulBaset** [reactjs/translations.react.dev#296]
Unfortunately, it appears that the current maintainers of the Arabic translation have been inactive for a prolonged period of time. Nobody reviews the PRs. So I'am interested in taking over some work.

Allow me to introduce myself and provide some information about my translation experience:

1. Native Arabic Speaker.
1. graduated from Alazhar Translation Center.
1. Part-time Translator at localistars.com.

Furthermore, I have already made substantial contributions to the Arabic translation of ar.reactjs.dev. Here is a list of pull requests I have submitted:

- [Tutorial tic-tac-toe](https://github.com/reactjs/ar.react.dev/pull/469)
- [Add React to an existing project](https://github.com/reactjs/ar.react.dev/pull/473)
- [React Developer tools](https://github.com/reactjs/ar.react.dev/pull/476)
- [Render and Commit](https://github.com/reactjs/ar.react.dev/pull/478)
- [Editor Setup](https://github.com/reactjs/ar.react.dev/pull/479)
- [Writing markup with JSX](https://github.com/reactjs/ar.react.dev/pull/480)
- [Importing and Exporting Components](https://github.com/reactjs/ar.react.dev/pull/476)

Ahmed Abdelbaset

**Comment by gaearon** [comment]
Thanks, I've added you as an admin.
