### ISSUE TITLE
Translation Bot has stopped working completely

### ISSUE THREAD

**Issue by smikitky** [reactjs/translations.react.dev#315]
The React docs translation bot has stopped working because "there hasn't been activity in this repository for at least 60 days". Please resume the scheduled run so we can start translating the new React 19 blog posts.

Related docs: https://docs.github.com/en/actions/using-workflows/disabling-and-enabling-a-workflow

> Warning: To prevent unnecessary workflow runs, scheduled workflows may be disabled automatically. When a public repository is forked, scheduled workflows are disabled by default. In a public repository, scheduled workflows are automatically disabled when no repository activity has occurred in 60 days.

@gaearon @rickhanlonii @harish-sethuraman

<img width="1108" alt="image" src="https://github.com/reactjs/translations.react.dev/assets/7779406/75ef427b-032e-474e-ab98-0d645b15cdde">

**Comment by rickhanlonii** [comment]
@smikitky what repo is that from?

**Comment by smikitky** [comment]
@rickhanlonii _This_ repo (https://github.com/reactjs/translations.react.dev). Click one of "Sync CI" on the left and I think you can see the message.

**Comment by rickhanlonii** [comment]
Ok cool, I re-enabled the workflows and triggered a new run for each batch: https://github.com/reactjs/translations.react.dev/actions/workflows/sync-batch-1.yml

lmk if there are any other issues

**Comment by rickhanlonii** [comment]
Looks like a few batches failed due to rate-limits, I'll have to wait and re-run them later

**Comment by rickhanlonii** [comment]
All batches completed and should continue on schedule next week
