### ISSUE TITLE
Add Korean to the list on translations.react.dev

### ISSUE THREAD

**Issue by airman5573** [reactjs/translations.react.dev#318]
We have a fully translated Korean version of the React documentation available at https://ko.react.dev/.

I'd like to request adding Korean to the list of languages on translations.react.dev.

Could you please provide guidance on how we can include Korean in this list? This addition would greatly help Korean-speaking developers find and access the translated documentation more easily.

Thank you for your consideration.

**Comment by lumirlumir** [comment]
해당 이슈는 ko.react.dev의 [#1](https://github.com/reactjs/ko.react.dev/issues/1#issuecomment-2370202109)이 close되어 발생한 것으로 확인되었습니다.

내일 쯤 현재 레포의 github workflows에 의해 sync action이 진행되면 자동으로 반영될 것 같으니, 확인해 보시고 현재 이슈 close 하셔도 될 것 같습니다. @airman5573

**Comment by airman5573** [comment]
This is resolved
